String.toLocaleString({
  "en": {
    "%game-intro"           : "Join the <strong>Roundels!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>, and additionally owes a lot to  <a href=\"http://git.io/cupcakes\">Cupcakes 2048</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'underground',
    '%4'                    : 'overground',
    '%8'                    : 'tramlink',
    '%16'                   : 'DLR',
    '%32'                   : 'crossrail',
    '%64'                   : 'coaches',
    '%128'                  : 'dial-a-ride',
    '%256'                  : 'river',
    '%512'                  : 'taxi private hire',
    '%1024'                 : 'streets',
    '%2048'                 : 'glasgow',
    '%4096'                 : 'edinburgh',
    '%8192'                 : 'northlink',
    '%p0'                   : 'underground',
    '%p4'                   : 'overground',
    '%p8'                   : 'tramlink',
    '%p16'                  : 'DLR',
    '%p32'                  : 'crossrail',
    '%p64'                  : 'coaches',
    '%p128'                 : 'dial-a-ride',
    '%p256'                 : 'river',
    '%p512'                 : 'taxi private hire',
    '%p1024'                : 'streets',
    '%p2048'                : 'glasgow',
    '%p4096'                : 'edinburgh',
    '%p8192'                : 'northlink'
  }

});
